export const category = [
  { value: 'Digital', label: 'Digital' },
  { value: 'OOH', label: 'OOH' },
  // { value: "Print", label: "Print" },
  // { value: "I.P", label: "I.P" },
  { value: 'TV', label: 'Television' },
  { value: 'Radio', label: 'Radio' },
  { value: 'Newspaper', label: 'Newspaper' },
  // { value: "Magazine", label: "Magazine" },
  // { value: "Outdoor", label: "Outdoors" },
  // { value: "BTL", label: "BTL" },
];

export const subCategory = [
  // { value: "Social Media", label: "Social Media", category: "", icon:"/icon/digital.png" , url:"/social-media"},
  {
    value: 'OOH',
    label: 'OOH',
    category: 'OOH',
    icon: '/icon/ooh.png',
    url: '/dashboard/product/ooh',
  },
  // { value: "PPC", label: "PPC", category: "", icon:"/icon/digital.png" , url:"/ppc"},
  // { value: "Email", label: "Email", category: "", icon:"/icon/digital.png" ,url:"/email"},
  {
    value: 'Influencers',
    label: 'Influencers',
    category: '',
    icon: '/icon/digital.png',
    url: '/dashboard/product/influencer',
  },
  // { value: "Billboards", label: "Billboards", category: "", icon:"/icon/digital.png" , url:"/billboard"},
  {
    value: 'Newspaper',
    label: 'Newspaper',
    category: 'Print',
    icon: '/icon/print.png',
    url: '/dashboard/product/newspaper',
  },
  {
    value: 'Magazine',
    label: 'Magazine',
    category: 'Print',
    icon: '/icon/magazine.png',
    url: '/dashboard/product/magazine',
  },
  // { value: "Events", label: "Events", category: "", icon:"/icon/digital.png" , url:"/events"},
  // { value: "Movies", label: "Movies", category: "", icon:"/icon/digital.png" , url:"/movie"},
  // { value: "Web Series", label: "Web Series", category: "", icon:"/icon/digital.png" , url:"/web-series"},
  // { value: "Trade Shows", label: "Trade Shows", category: "", icon:"/icon/digital.png" , url:"/trade-show"},
  {
    value: 'TV',
    label: 'TV',
    category: 'TV',
    icon: '/icon/tv.png',
    url: '/dashboard/product/tv',
  },
  {
    value: 'Radio',
    label: 'Radio',
    category: '',
    icon: '/icon/radio.png',
    url: '/dashboard/product/radio',
  },
];

export const tags = [
  {
    category: 'Actors',
    subCategory: [
      'TV Shows',
      'Soap Operas',
      'Reality Shows',
      'Talk Shows',
      'Comic-Con',
      'Movies',
      'Web Series',
      'Documentaries',
      'Comedy',
      'Stand-Up Comedy',
      'Film Festivals',
      'Awards Events',
      'Classics and Indies',
      'Voice Acting',
      'Dubbing Artists',
      'Bollywood Celebrities',
      'Streaming Platforms',
      'Gaming Industry',
      'Entertainment Events',
      'Festivals',
      'TV Reality Shows',
      'Motivational Speakers',
    ],
  },
  {
    category: 'Creators',
    subCategory: [
      'Influencers',
      'Vloggers',
      'Podcasters',
      'Gamers',
      'Food Bloggers',
      'Travel Vloggers',
      'Tech Influencers',
      'Filmmakers',
      'Animators',
      'Fashion Bloggers',
      'Beauty Influencers',
      'Comedian',
      'Reviewers',
      'DIY Creators',
      'Fitness Influencers',
      'Bollywood Vloggers',
      'Cooking',
      'Music Producers',
      'Dance Choreographers',
      'Boxing',
    ],
  },
  {
    category: 'Sportsperson',
    subCategory: [
      'Cricket',
      'Kabaddi',
      'Football',
      'Badminton',
      'Hockey',
      'Pro Wrestling',
      'Table Tennis',
      'Wrestling',
      'Basketball',
      'Athletics',
      'Kabaddi',
      'Soccer',
      'Badminton',
      'Cricket Commentators',
      'Indian Wrestling',
      'Indian Super League (ISL)',
      'Athletics',
      'Chess',
      'Cricket Legends',
    ],
  },
  {
    category: 'Business Professional',
    subCategory: [
      'Fashion Industry',
      'Retail',
      'Marketing',
      'Sales',
      'Technology',
      'Finance',
      'Hospitality',
      'Manufacturing',
      'Real Estate',
      'Marketing',
      'Consulting',
      'E-commerce',
      'Business Development',
      'Transportation',
      'Logistics',
      'Energy',
      'Engineering',
      'Insurance',
      'Finance',
      'Pharmaceuticals',
      'Research',
      'Telecommunications',
      'Engineering',
      'Food & Beverage',
      'Operations',
      'Banking',
      'Finance',
      'Retail',
      'Sales',
      'Marketing',
      'Human Resources',
      'Business Development',
    ],
  },
  {
    category: 'Working Professional',
    subCategory: [],
  },
  {
    category: 'Musician',
    subCategory: [
      'Bollywood Music',
      'Indian Hip Hop',
      'Indian Pop',
      'Folk Music',
      'Classical Music',
      'Indie Music',
      'Devotional Music',
      'Sufi Music',
      'Fusion Music',
      'Bhangra',
      'Carnatic Music',
      'Electronic Dance Music (EDM)',
      'Ghazals',
      'Indian Classical',
      'Rabindra Sangeet',
      'Kollywood Music',
      'Tollywood Music',
      'Marathi Music',
      'Punjabi Music',
      'Rajasthani Folk Music',
      'Disc Jockey (DJ)',
    ],
  },
];

export const location = [
  { value: 'Delhi', label: 'Delhi' },
  { value: 'Mumbai', label: 'Mumbai' },
  { value: 'Bengaluru', label: 'Bengaluru' },
  { value: 'Hyderabad', label: 'Hyderabad' },
  { value: 'Kolkata', label: 'Kolkata' },
  { value: 'Chennai', label: 'Chennai' },
  { value: 'Pune', label: 'Pune' },
  { value: 'Jaipur', label: 'Jaipur' },
  { value: 'Ahmedabad', label: 'Ahmedabad' },
  { value: 'Surat', label: 'Surat' },
  { value: 'Visakhapatnam', label: 'Visakhapatnam' },
  { value: 'Indore', label: 'Indore' },
  { value: 'Agra', label: 'Agra' },
  { value: 'Lucknow', label: 'Lucknow' },
  { value: 'Kochi', label: 'Kochi' },
  { value: 'Nagpur', label: 'Nagpur' },
  { value: 'Chandigarh', label: 'Chandigarh' },
  { value: 'Vadodara', label: 'Vadodara' },
  { value: 'Varanasi', label: 'Varanasi' },
  { value: 'Nashik', label: 'Nashik' },
  { value: 'Kanpur', label: 'Kanpur' },
  { value: 'Bhopal', label: 'Bhopal' },
  { value: 'Patna', label: 'Patna' },
  { value: 'Madurai', label: 'Madurai' },
  { value: 'Amritsar', label: 'Amritsar' },
  { value: 'Prayagraj', label: 'Prayagraj' },
  { value: 'Jodhpur', label: 'Jodhpur' },
  { value: 'Aurangabad', label: 'Aurangabad' },
  { value: 'Ludhiana', label: 'Ludhiana' },
  { value: 'Rajkot', label: 'Rajkot' },
  { value: 'Bhubaneswar', label: 'Bhubaneswar' },
  { value: 'Guwahati', label: 'Guwahati' },
  { value: 'Udaipur', label: 'Udaipur' },
  { value: 'Meerut', label: 'Meerut' },
  { value: 'Coimbatore', label: 'Coimbatore' },
  { value: 'Jamshedpur', label: 'Jamshedpur' },
  { value: 'Dehradun', label: 'Dehradun' },
  { value: 'Mangaluru', label: 'Mangaluru' },
  { value: 'Dhanbad', label: 'Dhanbad' },
  { value: 'Vijayawada', label: 'Vijayawada' },
  { value: 'Jabalpur', label: 'Jabalpur' },
  { value: 'Gwalior', label: 'Gwalior' },
  { value: 'Ranchi', label: 'Ranchi' },
  { value: 'Raipur', label: 'Raipur' },
  { value: 'Thiruvananthapuram', label: 'Thiruvananthapuram' },
  { value: 'Puducherry', label: 'Puducherry' },
  { value: 'Kota', label: 'Kota' },
  { value: 'Noida', label: 'Noida' },
  { value: 'Gurugram', label: 'Gurugram' },
];

export const languages = [
  { label: 'English', value: 'English' },
  { label: 'Hindi', value: 'Hindi' },
  { label: 'Bengali', value: 'Bengali' },
] as const;
export const durations = [
  { value: '10 sec', label: '10 sec' },
  { value: '15 sec', label: '15 sec' },
  { value: '20 sec', label: '20 sec' },
  { value: '30 sec', label: '30 sec' },
];
export const timeslots = [
  { value: '7-9 am', label: '7-9 am' },
  { value: '9-12 noon', label: '9-12 noon' },
  { value: '12-7 pm', label: '12-7 pm' },
  { value: '7-8 pm', label: '7-8 pm' },
  { value: '8-11 pm', label: '8-11 pm' },
];

// ................OOH.......................
export const oohLighting = [
  { value: 'BACK LIT', label: 'BACK LIT' },
  { value: 'FRONT LIT', label: 'FRONT LIT' },
  { value: 'LED', label: 'LED' },
  { value: 'NON LIT', label: 'NON LIT' },
];

export const oohAdType = [
  { value: 'Bus Shelter', label: 'Bus Shelter' },
  { value: 'Digital Screen', label: 'Digital Screen' },
  { value: 'Hoarding', label: 'Hoarding' },
  { value: 'Metro Pillar', label: 'Metro Pillar' },
  { value: 'Pole Kiosk', label: 'Pole Kiosk' },
  { value: 'Road Median', label: 'Road Median' },
  { value: 'Skywalk', label: 'Skywalk' },
];

// ................Newspaper.......................

export const sections = [
  { label: 'Recruitment Job', value: 'Recruitment Job' },
  { label: 'Matrimonial', value: 'Matrimonial' },
  { label: 'Change of Name', value: 'Change of Name' },
  {
    label: 'Obituary (Death Announcement)',
    value: 'Obituary (Death Announcement)',
  },
  { label: 'Public Tender Notices', value: 'Public Tender Notices' },
  { label: 'Business', value: 'Business' },
  { label: 'Education', value: 'Education' },
  { label: 'Property Real Estate', value: 'Property Real Estate' },
  { label: 'Lost and Found', value: 'Lost and Found' },
  { label: 'Marriage Bureau', value: 'Marriage Bureau' },
  {
    label: 'Remembrance (Unforgettable)',
    value: 'Remembrance (Unforgettable)',
  },
  { label: 'Services', value: 'Services' },
  { label: 'Retail/Shopping', value: 'Retail/Shopping' },
  { label: 'Personal Announcement', value: 'Personal Announcement' },
  { label: 'Computers and Hardware', value: 'Computers and Hardware' },
  { label: 'Astrology', value: 'Astrology' },
  { label: 'Vehicles Automobiles', value: 'Vehicles Automobiles' },
  { label: 'Tours and Travel', value: 'Tours and Travel' },
  { label: 'Entertainment', value: 'Entertainment' },
  { label: 'Real Estate Selling', value: 'Real Estate Selling' },
] as const;

export const printCirculations = [
  { label: 'Annual', value: 'Annual' },
  { label: 'Bi-Monthly', value: 'Bi-Monthly' },
  { label: 'Daily', value: 'Daily' },
  { label: 'Fortnightly', value: 'Fortnightly' },
  { label: 'Half Yearly', value: 'Half Yearly' },
  { label: 'Monthly', value: 'Monthly' },
  { label: 'Quarterly', value: 'Quarterly' },
  { label: 'Tri-Annual', value: 'Tri-Annual' },
  { label: 'Weekly', value: 'Weekly' },
] as const;
export const newspaperType = [
  { label: 'Full Page', value: 'Full Page' },
  { label: 'Horizontal Half Page', value: 'Horizontal Half Page' },
  { label: 'Vertical Half page', value: 'Vertical Half page' },
  { label: 'Quarter Page', value: 'Quarter Page' },
  { label: 'Jacket Front Side', value: 'Jacket Front Side' },
  { label: 'Jacket Back Side', value: 'Jacket Back Side' },
  { label: 'Pointer Ads', value: 'Pointer Ads' },
  { label: 'Skybus', value: 'Skybus' },
  { label: 'Custom-sized', value: 'Custom-sized' },
] as const;
export const dimensions = [
  {
    label: 'Full Page 33 cm x 52 cm (wxh)',
    value: 'Full Page 33 cm x 52 cm (wxh)',
  },
  {
    label: 'Horizontal Half Page 33 cm x 25 cm (wxh)',
    value: 'Horizontal Half Page 33 cm x 25 cm (wxh)',
  },
  {
    label: 'Vertical Half page 16 cm x 52 cm (wxh)',
    value: 'Vertical Half page 16 cm x 52 cm (wxh)',
  },
  {
    label: 'Quarter Page 16 cm x 25 cm (wxh)',
    value: 'Quarter Page 16 cm x 25 cm (wxh)',
  },
  {
    label: 'Jacket Front Side 33cmx48cm (wxh)',
    value: 'Jacket Front Side 33cmx48cm (wxh)',
  },
  {
    label: 'Jacket Back Side 33cmx52cm (wxh)',
    value: 'Jacket Back Side 33cmx52cm (wxh)',
  },
  { label: 'Pointer Ads 4cmx 5cm (wxh)', value: 'Pointer Ads 4cmx 5cm (wxh)' },
  { label: 'Skybus 33cmx5cm (wxh)', value: 'Skybus 33cmx5cm (wxh)' },
  {
    label: 'Custom-sized 4 cm (wide) * 5 cm (long)',
    value: 'Custom-sized 4 cm (wide) * 5 cm (long)',
  },
  {
    label: 'Custom-sized 8 cm (wide) * 8 cm (long)',
    value: 'Custom-sized 8 cm (wide) * 8 cm (long)',
  },
  {
    label: 'Custom-sized 8 cm (wide) * 12 cm (long)',
    value: 'Custom-sized 8 cm (wide) * 12 cm (long)',
  },
  {
    label: 'Custom-sized 12 cm (wide) * 20 cm (long)',
    value: 'Custom-sized 12 cm (wide) * 20 cm (long)',
  },
  {
    label: 'Custom-sized 16 cm (wide) * 20 cm (long)',
    value: 'Custom-sized 16 cm (wide) * 20 cm (long)',
  },
  { label: 'Advertorial', value: 'Advertorial' },
  { label: 'Public Notice', value: 'Public Notice' },
  { label: 'Obituary Ads', value: 'Obituary Ads' },
  { label: 'Front Page Centre Strip', value: 'Front Page Centre Strip' },
  { label: 'Text Classified ads', value: 'Text Classified ads' },
  { label: 'Display Classified Ads', value: 'Display Classified Ads' },
] as const;

// ................Magazine.......................

export const magazineCategories = [
  { label: 'Agriculture And Farming', value: 'Agriculture And Farming' },
  { label: 'Airline', value: 'Airline' },
  {
    label: 'Art, Culture And Literature',
    value: 'Art, Culture And Literature',
  },
  { label: 'Automobile', value: 'Automobile' },
  { label: 'Business', value: 'Business' },
  { label: 'Clubs', value: 'Clubs' },
  { label: 'Defence', value: 'Defence' },
  { label: 'Education', value: 'Education' },
  { label: 'Entertainment', value: 'Entertainment' },
  { label: 'Environment', value: 'Environment' },
  { label: 'Fashion And Lifestyle', value: 'Fashion And Lifestyle' },
  { label: 'Food And Beverage', value: 'Food And Beverage' },
  { label: 'Gaming And Sports', value: 'Gaming And Sports' },
  { label: 'General Interest', value: 'General Interest' },
  { label: 'Health', value: 'Health' },
  {
    label: 'Healthcare And Medical Journals',
    value: 'Healthcare And Medical Journals',
  },
  { label: 'Import And Export', value: 'Import And Export' },
  { label: 'Inflight', value: 'Inflight' },
  {
    label: 'Interior Design And Architecture',
    value: 'Interior Design And Architecture',
  },
  { label: 'IT, Computer And Animation', value: 'IT, Computer And Animation' },
  { label: 'Legal And Taxation', value: 'Legal And Taxation' },
  { label: 'Lifestyle', value: 'Lifestyle' },
  { label: 'Logistics', value: 'Logistics' },
  {
    label: 'Manufacturing And Engineering',
    value: 'Manufacturing And Engineering',
  },
  { label: 'Mom And Kids', value: 'Mom And Kids' },
  { label: 'News', value: 'News' },
  { label: 'Petroleum And Chemical', value: 'Petroleum And Chemical' },
  { label: 'Photography And Wildlife', value: 'Photography And Wildlife' },
  { label: 'Power And Electrical', value: 'Power And Electrical' },
  { label: 'Real Estate', value: 'Real Estate' },
  { label: 'Retail', value: 'Retail' },
  { label: 'Salon And Spa', value: 'Salon And Spa' },
  {
    label: 'Science And Related Journals',
    value: 'Science And Related Journals',
  },
  { label: 'SME And Startup', value: 'SME And Startup' },
  { label: 'Spiritual', value: 'Spiritual' },
  { label: 'Steel And Metal', value: 'Steel And Metal' },
  { label: 'Technology', value: 'Technology' },
  { label: 'Textile', value: 'Textile' },
  { label: 'Travel', value: 'Travel' },
  { label: 'Travel And Tourism', value: 'Travel And Tourism' },
  { label: 'Water, Plumbing And Pumps', value: 'Water, Plumbing And Pumps' },
] as const;

export const magazineAdTypes = [
  { label: 'Advertorial', value: 'Advertorial' },
  { label: 'Agency Fee', value: 'Agency Fee' },
  { label: 'Belly Band', value: 'Belly Band' },
  { label: 'Bookmark', value: 'Bookmark' },
  { label: 'Bound Bookmark', value: 'Bound Bookmark' },
  { label: 'Classifieds', value: 'Classifieds' },
  { label: 'E-Copy Options', value: 'E-Copy Options' },
  { label: 'Quarter Page', value: 'Quarter Page' },
  { label: 'Strip', value: 'Strip' },
  { label: 'Full Page', value: 'Full Page' },
  { label: 'Half Page', value: 'Half Page' },
  { label: 'Inside Back Cover', value: 'Inside Back Cover' },
  { label: 'Inside Front cover', value: 'Inside Front cover' },
  { label: 'Popular Inflight Magazines', value: 'Popular Inflight Magazines' },
  { label: 'Cover Page', value: 'Cover Page' },
  { label: 'Double Spread', value: 'Double Spread' },
  { label: 'Gate Fold', value: 'Gate Fold' },
  { label: 'Premium Inflight', value: 'Premium Inflight' },
] as const;

export const magazineDimensions = [
  { label: 'Full Page 8.5x11in', value: 'Full Page 8.5x11in' },
  { label: '2page Spread 17x11in', value: '2page Spread 17x11in' },
  { label: '2./3page 8.5x.7.25in', value: '2./3page 8.5x.7.25in' },
  { label: '1/2page 8.5x5.5in', value: '1/2page 8.5x5.5in' },
  { label: '1/2 vertical 4.25x11in', value: '1/2 vertical 4.25x11in' },
  {
    label: '1/3 page horizontal 8.5x3.25in',
    value: '1/3 page horizontal 8.5x3.25in',
  },
  {
    label: '1/3 page vertical 2.75x11in',
    value: '1/3 page vertical 2.75x11in',
  },
  { label: '1/4 page 4.25x5.5in', value: '1/4 page 4.25x5.5in' },
] as const;
